default_stages: [pre-commit, pre-push]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files # Prevent giant files from being committed
  - id: check-case-conflict     # Check for files with names that would conflict on a case-insensitive filesystem
  - id: check-merge-conflict    # Check for files that contain merge conflict strings
  - id: check-symlinks          # Checks for symlinks which do not point to anything
  - id: check-yaml              # Checks yaml files for syntax errors
  - id: detect-private-key      # Checks for the existence of private keys
  - id: end-of-file-fixer       # Makes sure files end in a newline and only a newline
  - id: mixed-line-ending       # Replaces or checks mixed line ending
  - id: trailing-whitespace     # Trims trailing whitespace
    args: [--markdown-linebreak-ext=md]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.0
  hooks:
    - id: ruff
      args: [--fix]
      types_or: [ python, pyi, jupyter ]
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
    - id: mypy
      additional_dependencies: [types-PyYAML, types-requests]

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
    - id: shellcheck
